version: '3'

services:
  postgres:
    container_name: bot_db
    restart: always
    image: postgres:16
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

    ports:
      - "5432:5432"
    env_file:
      - .env